RTC 386
jellyfish-dev/python-server-sdk pull request #15
Opened 2023-10-20 12:40 UTC by Rados13

Related to: https://github.com/jellyfish-dev/jellyfish/pull/104
Related to: https://github.com/jellyfish-dev/elixir_server_sdk/pull/37

After these changes, tests can be run only inside the docker. That's why a poetry command `ci_test` was added.
Tests can be run only inside docker because the jellyfish container can't access services running on the host OS through the `localhost` address.
A lot of changes were due to the running formatter. To avoid this type of situation in the future, a formatting check was added to CI.

2023-10-23 11:41 UTC, roznawsk requested changes
Lots of good changes!
I like the improvements of poetry - adding the scripts for testing and checking lint and format.
I wonder if we should be testing every new feature in the SDK's - in this case check the new fields in the HLS component. But I guess we don't have to, since we are already testing it in Jellyfish.

2023-10-23 11:41 UTC, roznawsk commented on tests/support/protos/jellyfish/__init__.py
I think we need this file, although the generated files are in two locations. The `tests/support/protos/jellyfish.py` should be removed. It should look like this:
<img width="213" alt="image" src="https://github.com/jellyfish-dev/python-server-sdk/assets/48837433/1b91abab-cf94-4828-97b8-3cea004e423a">

2023-10-23 11:41 UTC, roznawsk commented on jellyfish/events/_protos/protos/jellyfish/server_notifications_pb2.py
We use python-betterproto for generating python code from definitions. 
You can run `./compile_proto.sh` script to generate it.
This file seems to be generated by the official proto compiler which I don't think is user friendly.

2023-10-23 11:41 UTC, roznawsk commented on jellyfish/_notifier.py
> +
nitpick: add endline. I guess black would fix it in the next PR anyway

2023-10-24 15:27 UTC, Karolk99 approved these changes
Looks good but as @roznawsk mentioned we have to agree on a specific test approach for our SDKs.

2023-10-25 07:50 UTC, roznawsk approved these changes

2023-10-26 10:57 UTC, Karolk99 approved these changes

2023-10-26 18:38 UTC, roznawsk approved these changes

2023-10-27 07:55 UTC, merged